package server

import (
	"api-payments/controllers"
	"api-payments/middlewares"

	"api-payments/docs" // docs is generated by Swag CLI, you have to import it.

	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
)

// @title Swagger Example API
// @version 1.0
// @description api-payments
// @termsOfService http://swagger.io/terms/
// @securityDefinitions.apikey ApiKeyAuth
// @in header
// @name Access-token
// @host localhost:8082
// @BasePath /api
func initRoute() *gin.Engine {
	docs.SwaggerInfo.Schemes = []string{"http", "https"}

	route := gin.New()
	route.Use(gin.Logger())
	route.Use(gin.Recovery())

	api := route.Group("api")
	{
		api.Use(middlewares.Authenticate())
		orders := api.Group("backend/transactions")
		{
			order := new(controllers.BackendTransactionController)
			orders.POST("", order.Create)
			orders.GET("/:id", order.FindOne)
			orders.POST("/:id/cancel", order.Cancel)
		}
	}

	url := ginSwagger.URL("http://localhost:8082/swagger/doc.json") // The url pointing to API definition
	route.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler, url))
	return route
}
